---
version: 2
updates:
  # workflows
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    schedule:
      interval: "daily"

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      chainguard:
        patterns:
          - "chainguard.dev/*"
          - "github.com/chainguard-dev/*"
        update-types:
          - "minor"
          - "patch"
